language: php

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DB=mysql
      dist: precise

    - php: 5.4
      env: DB=mysql

branches:
  only:
    - master

before_install:
  # Speed up build time by disabling Xdebug
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  # Install PHP CodeSniffer.
  - composer self-update
  - composer install
  - phpenv rehash

script:
  - vendor/bin/phpcs --standard=PSR2 $(git diff-tree --no-commit-id --name-only -r `git log --format="%H" -n 1` | grep .php)

notifications:
  email: false
