language: php

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DB=mysql
      dist: precise

    - php: 5.4
      env: DB=mysql

branches:
  only:
    - master

before_script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_BUILD_ID
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_DIST
  - echo $TRAVIS_EVENT_TYPE
  - echo $TRAVIS_JOB_ID
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_SHA

script:
  - '! php -d error_reporting=32767 -l `git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php"` \; 2>&1 >&- | grep "^"'

notifications:
  email: false