language: php

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DB=mysql
      dist: precise

    - php: 5.4
      env: DB=mysql

branches:
  only:
    - master

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - echo $SNIFF
  - |
      composer global require wp-coding-standards/wpcs;
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs;
      phpcs --config-set standard infinum;

script:
  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'
  - sh -c "vendor/bin/phpcs . --extensions=php --runtime-set ignore_warnings_on_exit 1"

notifications:
  email: false
