language: php

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DB=mysql
      dist: precise

    - php: 5.4
      env: DB=mysql

branches:
  only:
    - master

before_script:
  - echo $TRAVIS_COMMIT_RANGE

script:
  - |
    echo "[DEBUG] Checking modified files"
    changed_files=`git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php"`
    echo "[DEBUG] Modified Files:"
    echo $changed_files
    if [ -z "$changed_files" ]; then 
      echo "[DEBUG] No *.php files found to check"
    else
      echo "[DEBUG] Checking files for errors..."
      ! php -d error_reporting=32767 -l `git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php"` \; 2>&1 >&- | grep "^"  
      echo "[DEBUG] Done"
    fi

notifications:
  email: false