language: php

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DB=mysql
      dist: precise

    - php: 5.4
      env: DB=mysql

branches:
  only:
    - master

before_script:
  - sh -c "composer global require 'phpunit/phpunit=3.7.33'"

script:
  - |
    files=`git diff-tree --no-commit-id --name-only -r  7a76bee`
    for file in $files; do
      echo $file
      php -d error_reporting=32767 -l $file \; 2>&1 >&- | grep "^"
    done


notifications:
  email: false
