language: php

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DB=mysql
      dist: precise

    - php: 5.4
      env: DB=mysql

branches:
  only:
    - master

before_script:
  - echo $TRAVIS_COMMIT_RANGE

script:
  - |
    changed_files=`git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php"`
    if [ '$changed_files' != '' ]; then 
      wheree=1
      ! php -d error_reporting=32767 -l `git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php"` \; 2>&1 >&- | grep "^"
    else
      wheree=2      
    fi
    echo $wheree

notifications:
  email: false