language: php

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DB=mysql
      dist: precise

    - php: 5.4
      env: DB=mysql

branches:
  only:
    - master

before_script:
  - echo $TRAVIS_COMMIT_RANGE

script:
  - |
    CHANGED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php")
    echo $CHANGED_FILES
    if [ $CHANGED_FILES != '' ]; then
      ! php -d error_reporting=32767 -l `git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php"` \; 2>&1 >&- | grep "^"
    fi

notifications:
  email: false