language: php

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DB=mysql
      dist: precise

    - php: 5.4
      env: DB=mysql

branches:
  only:
    - master

before_script:
  - echo $TRAVIS_COMMIT_RANGE

script:
  - |
    if [ '$TRAVIS_EVENT_TYPE' == 'pull_request' ]; then 
      changed_files=$(git diff --name-only HEAD...$TRAVIS_BRANCH | grep "php")
    else
      changed_files=$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php")
    fi
    echo $changed_files

notifications:
  email: false