language: php

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DB=mysql
      dist: precise

    - php: 5.4
      env: DB=mysql

branches:
  only:
    - master

before_script:
  - echo $TRAVIS_COMMIT_RANGE

script:
  - |
    changed_files=`git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php"`
    echo "[DEBUG] [changed_files]" $changed_files
    if [ '$changed_files' != '' ]; then 
      echo "[DEBUG] not empty changed_files"
      ! php -d error_reporting=32767 -l `git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php"` \; 2>&1 >&- | grep "^"
    else
      echo "[DEBUG] empty changed_files"
      whereee=2      
    fi

notifications:
  email: false