language: php

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DB=mysql
      dist: precise

    - php: 5.4
      env: DB=mysql

branches:
  only:
    - master

before_script:
  - echo $TRAVIS_COMMIT_RANGE

script:
  - |
    echo "[DEBUG] Checking modified files"
    changed_files=`git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php"`
    status=0
    if [ -z "$changed_files" ]; then 
      echo "[DEBUG] No *.php files found to check"
    else
      echo "[DEBUG] Modified Files:"
      echo $changed_files
      echo "[DEBUG] Checking files for errors..."
      phperrors=$( php -d error_reporting=32767 -l `git diff --name-only $TRAVIS_COMMIT_RANGE | grep "php"` \; 2>&1 >&- )
      if [ -z "$phperrors" ]; then 
        echo "[DEBUG] No errors found"
      else
        echo "[DEBUG] Errors found:"
        echo $phperrors
        status=1
      fi
    fi
    echo "[DEBUG] Done"
    exit $status

notifications:
  email: false